spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: alchemy-wiki
  main:
    allow-bean-definition-overriding: true
  devtools:
    add-properties: true
graphql:
  servlet:
    enabled: true
    corsEnabled: true
    # if you want to @ExceptionHandler annotation for custom GraphQLErrors
    exception-handlers-enabled: true
    contextSetting: PER_REQUEST_WITH_INSTRUMENTATION
